### PR TITLE
add a new link variant : Custom Link

### PR DESCRIPTION
**Pull request by FahimNsr**

### CODE REVIEW

**Comment by lorenzulrich** [comment]
@FahimNsr Without further description it's a little hard to imagine what the idea behind this feature was?

**Comment by mhsdesign** [comment]
I think its for entering links that are not convered by the other tabs.

For example 

```
    isSuitableFor: (link: ILink) => !link.href.startsWith('asset://') && !link.href.startsWith('mailto:')
         && !link.href.startsWith('node://') && !link.href.startsWith('tel:')
         && !link.href.startsWith('http://') && !link.href.startsWith('https://'),
```

we only handle links with protocols we dont know.

But there is a catch. If we enter a link still starting with a known protocol, but continue to write something the default implementation doesnt cover, like adding an anchor to asset uris: `asset://456877568#anchor`. When opening the editor the next time this link will be opened in the asset editor again, which leads to loss of the anchor.
... this is just an edgecase we need to be aware of.

For cases like relative urls, fragments and unknown protocols it would work:

- `somepage/foo.html`
- `#foo`
- `myprotocol://foo.de`

but we should rather focus on your real usecase ;) I dont think an editor knows about every detail of the uri specification and knows what to put in there.

**Comment by mficzel** [comment]
I understand the feature and think that it is a valid usecase a description in the pr would be nice to really get the use-case.

It might make sense to have this as opt-in feature that has to be enabled.

**Comment by lorenzulrich** [comment]
@mficzel IMO it would have been ideal to disable this editor by default. This was released in a minor version and so everyone updating will have an additional link editor they might not need. Not a problem in my WIP project but just as a feedback regarding versioning. Thanks!

**Comment by mhsdesign** [comment]
@lorenzulrich i agree especially cause its such an edgecase feature and some editors might use it as footgun.

I thought we agreed on this? ^^
> It might make sense to have this as opt-in feature that has to be enabled.

im a bit unhappy that this was merged so eagerly by @andrehoffmann30 ... but nothing a followup fix cant solve ;)

**Pull request merged**
