### PR TITLE
BUGFIX: Use native Neos UI Dialog for link editor

### PR DESCRIPTION
**Pull request by grebaldi**
fixes: #39 

**The problem**

Dialog behavior in Neos UI has changed recently. Those changes collide with Sitegeist.Archaeoptryx' custom dialog implementation, which renders it unusable in the node creation dialog.

**The solution**

https://github.com/sitegeist/Sitegeist.Archaeopteryx/assets/2522299/58668079-c985-4f4d-babf-90dd23de2e3a

I replaced the custom dialog implementation with Neos UI's native dialog. For this I needed to (hackily) adjust the dialog's layout behavior, which lead to a follow-up PR in Neos.Neos.Ui.

### CODE REVIEW

**Review by crydotsnake — APPROVED** [review]
Works great!

**Comment by crydotsnake** [comment]
Could you maybe take a look at it? @nezaniel

**Comment by crydotsnake** [comment]
ping @mficzel / @nezaniel

**Comment by mhsdesign** [comment]
Thank you so much for taking care ❤️ 
This also fixes a bug when one tries to reedit a link from within the inspector, as the pending changes overlay will interfere:

Current dev-main
https://github.com/sitegeist/Sitegeist.Archaeopteryx/assets/85400359/097ccd0e-37f6-4fd9-85e5-2e1e7e7f4eea

Your fix
https://github.com/sitegeist/Sitegeist.Archaeopteryx/assets/85400359/15f92d8d-d3ab-4ed6-8945-dbf372798a69

Additionally its a nice touch to have the orange border and shake animation when trying to click outside of the dialog. Previously the dialog wouldn't close either but just stay as is.

**Comment by mhsdesign** [comment]
Though we have to adjust the composer json to be only compatible with neos ui patches with this fix - will do this later ;)

**Comment by crydotsnake** [comment]
Would be awesome, if we could get this merged :)

**Pull request merged**
